# Generated by Django 2.1.4 on 2018-12-18 22:31

from django.db import migrations, models
import pricing.models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[(pricing.models.FeatureStatus('Input'), 'Input'), (pricing.models.FeatureStatus('Target'), 'Target')], default=pricing.models.FeatureStatus('Input'), max_length=10),
        ),
        migrations.AlterField(
            model_name='model',
            name='loss',
            field=models.CharField(choices=[(pricing.models.LossFunction('Gaussian'), 'Gaussian'), (pricing.models.LossFunction('Logistic'), 'Logistic'), (pricing.models.LossFunction('Poisson'), 'Poisson'), (pricing.models.LossFunction('Gamma'), 'Gamma')], default=pricing.models.LossFunction('Gaussian'), max_length=10),
        ),
    ]
