# Generated by Django 2.1.4 on 2019-01-08 13:01

from django.db import migrations, models
import django.db.models.functions.text
import pricing.models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_auto_20181231_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AddField(
            model_name='dataset',
            name='fn_filter',
            field=models.TextField(default=("def data_filter(row):\n    return row['HAB_hab'] == 'A'\n",)),
        ),
        migrations.AddField(
            model_name='dataset',
            name='fn_train',
            field=models.TextField(default="def data_train(row):\n    return row['Random'] != '9' and row['Random'] != '10'\n"),
        ),
        migrations.AddField(
            model_name='dataset',
            name='fn_transform',
            field=models.TextField(default=("def data_transform(row):\n    row['POL_mtcapass'] = int(math.log(float(row['POL_mtcapass'])))\n",)),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('Input', 'Input'), ('Target', 'Target'), ('Ignore', 'Ignore')], default=pricing.models.FeatureStatus('Input'), max_length=10),
        ),
    ]
