# Generated by Django 2.1.4 on 2019-01-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_auto_20190108_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='fn_filter',
            field=models.TextField(default="def data_filter(row):\n    return row['HAB_hab'] == 'A'\n"),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='fn_transform',
            field=models.TextField(default="def data_transform(row):\n    row['POL_mtcapass'] = int(math.log(float(row['POL_mtcapass'])))\n"),
        ),
    ]
