# Generated by Django 2.1.4 on 2019-01-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_auto_20190108_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='fn_transform',
            field=models.TextField(default="def data_transform(row):\n    return row['POL_mtcapass'] = int(math.log(float(row['POL_mtcapass'])))\n"),
        ),
    ]
