# Generated by Django 2.1.4 on 2019-01-09 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_auto_20190108_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='pricing.Feature'),
        ),
        migrations.AlterField(
            model_name='model',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='pricing.Feature'),
        ),
    ]
