# Generated by Django 2.1.4 on 2019-01-09 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_auto_20190109_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.Feature')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('feature.name')],
            },
        ),
        migrations.AlterField(
            model_name='model',
            name='features',
            field=models.ManyToManyField(related_name='features', to='pricing.ModelFeature'),
        ),
    ]
